version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    image: yasinsaeeniya/go-user-service:latest
    container_name: user-service
    depends_on:
      - mongo
    environment:
      - PRIVATE_KEY_PATH=/app/keys/private.key
      - PUBLIC_KEY_PATH=/app/keys/public.key
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=user_service
      - PORT=50051
      - JWT_EXP=24
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./keys:/app/keys
      - ./cmd/.env:/app/.env

volumes:
  mongo_data:
