// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: user-service/group/group.proto

package grouppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SelectedRoles []*SelectedRoles       `protobuf:"bytes,4,rep,name=selectedRoles,proto3" json:"selectedRoles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_user_service_group_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Group) GetSelectedRoles() []*SelectedRoles {
	if x != nil {
		return x.SelectedRoles
	}
	return nil
}

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_user_service_group_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{1}
}

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Permissions   []*Permission          `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_user_service_group_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{2}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type SelectedRoles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Permissions   []*Permission          `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectedRoles) Reset() {
	*x = SelectedRoles{}
	mi := &file_user_service_group_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectedRoles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedRoles) ProtoMessage() {}

func (x *SelectedRoles) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedRoles.ProtoReflect.Descriptor instead.
func (*SelectedRoles) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{3}
}

func (x *SelectedRoles) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *SelectedRoles) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type RequestSelectedRoles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSelectedRoles) Reset() {
	*x = RequestSelectedRoles{}
	mi := &file_user_service_group_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSelectedRoles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSelectedRoles) ProtoMessage() {}

func (x *RequestSelectedRoles) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSelectedRoles.ProtoReflect.Descriptor instead.
func (*RequestSelectedRoles) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{4}
}

func (x *RequestSelectedRoles) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RequestSelectedRoles) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=Group,proto3" json:"Group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupResponse) Reset() {
	*x = GroupResponse{}
	mi := &file_user_service_group_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupResponse) ProtoMessage() {}

func (x *GroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupResponse.ProtoReflect.Descriptor instead.
func (*GroupResponse) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{5}
}

func (x *GroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_user_service_group_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{6}
}

func (x *GetGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	SelectedRoles []*RequestSelectedRoles `protobuf:"bytes,3,rep,name=selectedRoles,proto3" json:"selectedRoles,omitempty"`
	TenantId      string                  `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_user_service_group_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{7}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGroupRequest) GetSelectedRoles() []*RequestSelectedRoles {
	if x != nil {
		return x.SelectedRoles
	}
	return nil
}

func (x *CreateGroupRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SelectedRoles []*RequestSelectedRoles `protobuf:"bytes,4,rep,name=selectedRoles,proto3" json:"selectedRoles,omitempty"`
	TenantId      string                  `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_user_service_group_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateGroupRequest) GetSelectedRoles() []*RequestSelectedRoles {
	if x != nil {
		return x.SelectedRoles
	}
	return nil
}

func (x *UpdateGroupRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_user_service_group_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_user_service_group_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_user_service_group_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{11}
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_user_service_group_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{12}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ListPaginationGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaginationGroupsRequest) Reset() {
	*x = ListPaginationGroupsRequest{}
	mi := &file_user_service_group_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaginationGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaginationGroupsRequest) ProtoMessage() {}

func (x *ListPaginationGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaginationGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListPaginationGroupsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{13}
}

func (x *ListPaginationGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPaginationGroupsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaginationGroupsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListPaginationGroupsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListPaginationGroupsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListPaginationGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	MetaData      *MetaData              `protobuf:"bytes,2,opt,name=metaData,proto3" json:"metaData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaginationGroupsResponse) Reset() {
	*x = ListPaginationGroupsResponse{}
	mi := &file_user_service_group_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaginationGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaginationGroupsResponse) ProtoMessage() {}

func (x *ListPaginationGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaginationGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListPaginationGroupsResponse) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{14}
}

func (x *ListPaginationGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListPaginationGroupsResponse) GetMetaData() *MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

type MetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalCounts   int32                  `protobuf:"varint,2,opt,name=totalCounts,proto3" json:"totalCounts,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,4,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	NextPage      int32                  `protobuf:"varint,5,opt,name=nextPage,proto3" json:"nextPage,omitempty"`
	Sort          string                 `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_user_service_group_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{15}
}

func (x *MetaData) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MetaData) GetTotalCounts() int32 {
	if x != nil {
		return x.TotalCounts
	}
	return 0
}

func (x *MetaData) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *MetaData) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *MetaData) GetNextPage() int32 {
	if x != nil {
		return x.NextPage
	}
	return 0
}

func (x *MetaData) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type GetByFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TeantId       string                 `protobuf:"bytes,2,opt,name=teant_id,json=teantId,proto3" json:"teant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByFilterRequest) Reset() {
	*x = GetByFilterRequest{}
	mi := &file_user_service_group_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByFilterRequest) ProtoMessage() {}

func (x *GetByFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_group_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByFilterRequest.ProtoReflect.Descriptor instead.
func (*GetByFilterRequest) Descriptor() ([]byte, []int) {
	return file_user_service_group_group_proto_rawDescGZIP(), []int{16}
}

func (x *GetByFilterRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetByFilterRequest) GetTeantId() string {
	if x != nil {
		return x.TeantId
	}
	return ""
}

var File_user_service_group_group_proto protoreflect.FileDescriptor

const file_user_service_group_group_proto_rawDesc = "" +
	"\n" +
	"\x1euser-service/group/group.proto\x12\x05group\"\x89\x01\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12:\n" +
	"\rselectedRoles\x18\x04 \x03(\v2\x14.group.SelectedRolesR\rselectedRoles\"R\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x81\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\vpermissions\x18\x04 \x03(\v2\x11.group.PermissionR\vpermissions\"e\n" +
	"\rSelectedRoles\x12\x1f\n" +
	"\x04role\x18\x01 \x01(\v2\v.group.RoleR\x04role\x123\n" +
	"\vpermissions\x18\x02 \x03(\v2\x11.group.PermissionR\vpermissions\"L\n" +
	"\x14RequestSelectedRoles\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"3\n" +
	"\rGroupResponse\x12\"\n" +
	"\x05Group\x18\x01 \x01(\v2\f.group.GroupR\x05Group\"!\n" +
	"\x0fGetGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaa\x01\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12A\n" +
	"\rselectedRoles\x18\x03 \x03(\v2\x1b.group.RequestSelectedRolesR\rselectedRoles\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"\xba\x01\n" +
	"\x12UpdateGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12A\n" +
	"\rselectedRoles\x18\x04 \x03(\v2\x1b.group.RequestSelectedRolesR\rselectedRoles\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\"$\n" +
	"\x12DeleteGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteGroupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x13\n" +
	"\x11ListGroupsRequest\":\n" +
	"\x12ListGroupsResponse\x12$\n" +
	"\x06groups\x18\x01 \x03(\v2\f.group.GroupR\x06groups\"\x90\x01\n" +
	"\x1bListPaginationGroupsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\"q\n" +
	"\x1cListPaginationGroupsResponse\x12$\n" +
	"\x06groups\x18\x01 \x03(\v2\f.group.GroupR\x06groups\x12+\n" +
	"\bmetaData\x18\x02 \x01(\v2\x0f.group.MetaDataR\bmetaData\"\xb4\x01\n" +
	"\bMetaData\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12 \n" +
	"\vtotalCounts\x18\x02 \x01(\x05R\vtotalCounts\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x04 \x01(\x05R\vcurrentPage\x12\x1a\n" +
	"\bnextPage\x18\x05 \x01(\x05R\bnextPage\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\tR\x04sort\"A\n" +
	"\x12GetByFilterRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x19\n" +
	"\bteant_id\x18\x02 \x01(\tR\ateantId2\xf7\x03\n" +
	"\fGroupService\x128\n" +
	"\bGetGroup\x12\x16.group.GetGroupRequest\x1a\x14.group.GroupResponse\x12>\n" +
	"\vCreateGroup\x12\x19.group.CreateGroupRequest\x1a\x14.group.GroupResponse\x12>\n" +
	"\vUpdateGroup\x12\x19.group.UpdateGroupRequest\x1a\x14.group.GroupResponse\x12C\n" +
	"\x10GetByFilterGroup\x12\x19.group.GetByFilterRequest\x1a\x14.group.GroupResponse\x12D\n" +
	"\vDeleteGroup\x12\x19.group.DeleteGroupRequest\x1a\x1a.group.DeleteGroupResponse\x12A\n" +
	"\n" +
	"ListGroups\x12\x18.group.ListGroupsRequest\x1a\x19.group.ListGroupsResponse\x12_\n" +
	"\x14ListPaginationGroups\x12\".group.ListPaginationGroupsRequest\x1a#.group.ListPaginationGroupsResponseB\n" +
	"Z\b/grouppbb\x06proto3"

var (
	file_user_service_group_group_proto_rawDescOnce sync.Once
	file_user_service_group_group_proto_rawDescData []byte
)

func file_user_service_group_group_proto_rawDescGZIP() []byte {
	file_user_service_group_group_proto_rawDescOnce.Do(func() {
		file_user_service_group_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_group_group_proto_rawDesc), len(file_user_service_group_group_proto_rawDesc)))
	})
	return file_user_service_group_group_proto_rawDescData
}

var file_user_service_group_group_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_user_service_group_group_proto_goTypes = []any{
	(*Group)(nil),                        // 0: group.Group
	(*Permission)(nil),                   // 1: group.Permission
	(*Role)(nil),                         // 2: group.Role
	(*SelectedRoles)(nil),                // 3: group.SelectedRoles
	(*RequestSelectedRoles)(nil),         // 4: group.RequestSelectedRoles
	(*GroupResponse)(nil),                // 5: group.GroupResponse
	(*GetGroupRequest)(nil),              // 6: group.GetGroupRequest
	(*CreateGroupRequest)(nil),           // 7: group.CreateGroupRequest
	(*UpdateGroupRequest)(nil),           // 8: group.UpdateGroupRequest
	(*DeleteGroupRequest)(nil),           // 9: group.DeleteGroupRequest
	(*DeleteGroupResponse)(nil),          // 10: group.DeleteGroupResponse
	(*ListGroupsRequest)(nil),            // 11: group.ListGroupsRequest
	(*ListGroupsResponse)(nil),           // 12: group.ListGroupsResponse
	(*ListPaginationGroupsRequest)(nil),  // 13: group.ListPaginationGroupsRequest
	(*ListPaginationGroupsResponse)(nil), // 14: group.ListPaginationGroupsResponse
	(*MetaData)(nil),                     // 15: group.MetaData
	(*GetByFilterRequest)(nil),           // 16: group.GetByFilterRequest
}
var file_user_service_group_group_proto_depIdxs = []int32{
	3,  // 0: group.Group.selectedRoles:type_name -> group.SelectedRoles
	1,  // 1: group.Role.permissions:type_name -> group.Permission
	2,  // 2: group.SelectedRoles.role:type_name -> group.Role
	1,  // 3: group.SelectedRoles.permissions:type_name -> group.Permission
	0,  // 4: group.GroupResponse.Group:type_name -> group.Group
	4,  // 5: group.CreateGroupRequest.selectedRoles:type_name -> group.RequestSelectedRoles
	4,  // 6: group.UpdateGroupRequest.selectedRoles:type_name -> group.RequestSelectedRoles
	0,  // 7: group.ListGroupsResponse.groups:type_name -> group.Group
	0,  // 8: group.ListPaginationGroupsResponse.groups:type_name -> group.Group
	15, // 9: group.ListPaginationGroupsResponse.metaData:type_name -> group.MetaData
	6,  // 10: group.GroupService.GetGroup:input_type -> group.GetGroupRequest
	7,  // 11: group.GroupService.CreateGroup:input_type -> group.CreateGroupRequest
	8,  // 12: group.GroupService.UpdateGroup:input_type -> group.UpdateGroupRequest
	16, // 13: group.GroupService.GetByFilterGroup:input_type -> group.GetByFilterRequest
	9,  // 14: group.GroupService.DeleteGroup:input_type -> group.DeleteGroupRequest
	11, // 15: group.GroupService.ListGroups:input_type -> group.ListGroupsRequest
	13, // 16: group.GroupService.ListPaginationGroups:input_type -> group.ListPaginationGroupsRequest
	5,  // 17: group.GroupService.GetGroup:output_type -> group.GroupResponse
	5,  // 18: group.GroupService.CreateGroup:output_type -> group.GroupResponse
	5,  // 19: group.GroupService.UpdateGroup:output_type -> group.GroupResponse
	5,  // 20: group.GroupService.GetByFilterGroup:output_type -> group.GroupResponse
	10, // 21: group.GroupService.DeleteGroup:output_type -> group.DeleteGroupResponse
	12, // 22: group.GroupService.ListGroups:output_type -> group.ListGroupsResponse
	14, // 23: group.GroupService.ListPaginationGroups:output_type -> group.ListPaginationGroupsResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_user_service_group_group_proto_init() }
func file_user_service_group_group_proto_init() {
	if File_user_service_group_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_group_group_proto_rawDesc), len(file_user_service_group_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_group_group_proto_goTypes,
		DependencyIndexes: file_user_service_group_group_proto_depIdxs,
		MessageInfos:      file_user_service_group_group_proto_msgTypes,
	}.Build()
	File_user_service_group_group_proto = out.File
	file_user_service_group_group_proto_goTypes = nil
	file_user_service_group_group_proto_depIdxs = nil
}
