// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: user-service/otp/otp.proto

package otppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OTP structure
type OTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"` // شماره موبایل یا ایمیل
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	Used          bool                   `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTP) Reset() {
	*x = OTP{}
	mi := &file_user_service_otp_otp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTP) ProtoMessage() {}

func (x *OTP) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTP.ProtoReflect.Descriptor instead.
func (*OTP) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{0}
}

func (x *OTP) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OTP) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *OTP) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OTP) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *OTP) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

// CRUD
type CreateOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,3,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOTPRequest) Reset() {
	*x = CreateOTPRequest{}
	mi := &file_user_service_otp_otp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOTPRequest) ProtoMessage() {}

func (x *CreateOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOTPRequest.ProtoReflect.Descriptor instead.
func (*CreateOTPRequest) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOTPRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *CreateOTPRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateOTPRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreateOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otp           *OTP                   `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOTPResponse) Reset() {
	*x = CreateOTPResponse{}
	mi := &file_user_service_otp_otp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOTPResponse) ProtoMessage() {}

func (x *CreateOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOTPResponse.ProtoReflect.Descriptor instead.
func (*CreateOTPResponse) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOTPResponse) GetOtp() *OTP {
	if x != nil {
		return x.Otp
	}
	return nil
}

type UpdateOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,3,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"`
	Used          bool                   `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOTPRequest) Reset() {
	*x = UpdateOTPRequest{}
	mi := &file_user_service_otp_otp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOTPRequest) ProtoMessage() {}

func (x *UpdateOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOTPRequest.ProtoReflect.Descriptor instead.
func (*UpdateOTPRequest) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateOTPRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOTPRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateOTPRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *UpdateOTPRequest) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

type UpdateOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otp           *OTP                   `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOTPResponse) Reset() {
	*x = UpdateOTPResponse{}
	mi := &file_user_service_otp_otp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOTPResponse) ProtoMessage() {}

func (x *UpdateOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOTPResponse.ProtoReflect.Descriptor instead.
func (*UpdateOTPResponse) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOTPResponse) GetOtp() *OTP {
	if x != nil {
		return x.Otp
	}
	return nil
}

type DeleteOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOTPRequest) Reset() {
	*x = DeleteOTPRequest{}
	mi := &file_user_service_otp_otp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOTPRequest) ProtoMessage() {}

func (x *DeleteOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOTPRequest.ProtoReflect.Descriptor instead.
func (*DeleteOTPRequest) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteOTPRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOTPResponse) Reset() {
	*x = DeleteOTPResponse{}
	mi := &file_user_service_otp_otp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOTPResponse) ProtoMessage() {}

func (x *DeleteOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOTPResponse.ProtoReflect.Descriptor instead.
func (*DeleteOTPResponse) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteOTPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOTPRequest) Reset() {
	*x = GetOTPRequest{}
	mi := &file_user_service_otp_otp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOTPRequest) ProtoMessage() {}

func (x *GetOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOTPRequest.ProtoReflect.Descriptor instead.
func (*GetOTPRequest) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{7}
}

func (x *GetOTPRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otp           *OTP                   `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOTPResponse) Reset() {
	*x = GetOTPResponse{}
	mi := &file_user_service_otp_otp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOTPResponse) ProtoMessage() {}

func (x *GetOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOTPResponse.ProtoReflect.Descriptor instead.
func (*GetOTPResponse) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{8}
}

func (x *GetOTPResponse) GetOtp() *OTP {
	if x != nil {
		return x.Otp
	}
	return nil
}

type ListOTPsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOTPsRequest) Reset() {
	*x = ListOTPsRequest{}
	mi := &file_user_service_otp_otp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOTPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOTPsRequest) ProtoMessage() {}

func (x *ListOTPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOTPsRequest.ProtoReflect.Descriptor instead.
func (*ListOTPsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{9}
}

type ListOTPsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otps          []*OTP                 `protobuf:"bytes,1,rep,name=otps,proto3" json:"otps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOTPsResponse) Reset() {
	*x = ListOTPsResponse{}
	mi := &file_user_service_otp_otp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOTPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOTPsResponse) ProtoMessage() {}

func (x *ListOTPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOTPsResponse.ProtoReflect.Descriptor instead.
func (*ListOTPsResponse) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{10}
}

func (x *ListOTPsResponse) GetOtps() []*OTP {
	if x != nil {
		return x.Otps
	}
	return nil
}

// Business Logic (Request / Validate OTP)
type RequestOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // شماره موبایل یا ایمیل
	TtlSeconds    int32                  `protobuf:"varint,2,opt,name=ttlSeconds,proto3" json:"ttlSeconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOTPRequest) Reset() {
	*x = RequestOTPRequest{}
	mi := &file_user_service_otp_otp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOTPRequest) ProtoMessage() {}

func (x *RequestOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOTPRequest.ProtoReflect.Descriptor instead.
func (*RequestOTPRequest) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{11}
}

func (x *RequestOTPRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *RequestOTPRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type RequestOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOTPResponse) Reset() {
	*x = RequestOTPResponse{}
	mi := &file_user_service_otp_otp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOTPResponse) ProtoMessage() {}

func (x *RequestOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOTPResponse.ProtoReflect.Descriptor instead.
func (*RequestOTPResponse) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{12}
}

func (x *RequestOTPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateOTPRequest) Reset() {
	*x = ValidateOTPRequest{}
	mi := &file_user_service_otp_otp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateOTPRequest) ProtoMessage() {}

func (x *ValidateOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateOTPRequest.ProtoReflect.Descriptor instead.
func (*ValidateOTPRequest) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateOTPRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *ValidateOTPRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ValidateOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateOTPResponse) Reset() {
	*x = ValidateOTPResponse{}
	mi := &file_user_service_otp_otp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateOTPResponse) ProtoMessage() {}

func (x *ValidateOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_otp_otp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateOTPResponse.ProtoReflect.Descriptor instead.
func (*ValidateOTPResponse) Descriptor() ([]byte, []int) {
	return file_user_service_otp_otp_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateOTPResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_user_service_otp_otp_proto protoreflect.FileDescriptor

const file_user_service_otp_otp_proto_rawDesc = "" +
	"\n" +
	"\x1auser-service/otp/otp.proto\x12\x03otp\"w\n" +
	"\x03OTP\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1c\n" +
	"\texpiresAt\x18\x04 \x01(\x03R\texpiresAt\x12\x12\n" +
	"\x04used\x18\x05 \x01(\bR\x04used\"b\n" +
	"\x10CreateOTPRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"ttlSeconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\"/\n" +
	"\x11CreateOTPResponse\x12\x1a\n" +
	"\x03otp\x18\x01 \x01(\v2\b.otp.OTPR\x03otp\"j\n" +
	"\x10UpdateOTPRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"ttlSeconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\x12\x12\n" +
	"\x04used\x18\x04 \x01(\bR\x04used\"/\n" +
	"\x11UpdateOTPResponse\x12\x1a\n" +
	"\x03otp\x18\x01 \x01(\v2\b.otp.OTPR\x03otp\"\"\n" +
	"\x10DeleteOTPRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x11DeleteOTPResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1f\n" +
	"\rGetOTPRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x0eGetOTPResponse\x12\x1a\n" +
	"\x03otp\x18\x01 \x01(\v2\b.otp.OTPR\x03otp\"\x11\n" +
	"\x0fListOTPsRequest\"0\n" +
	"\x10ListOTPsResponse\x12\x1c\n" +
	"\x04otps\x18\x01 \x03(\v2\b.otp.OTPR\x04otps\"O\n" +
	"\x11RequestOTPRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x1e\n" +
	"\n" +
	"ttlSeconds\x18\x02 \x01(\x05R\n" +
	"ttlSeconds\".\n" +
	"\x12RequestOTPResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"D\n" +
	"\x12ValidateOTPRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"+\n" +
	"\x13ValidateOTPResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid2\xad\x03\n" +
	"\n" +
	"OTPService\x12:\n" +
	"\tCreateOTP\x12\x15.otp.CreateOTPRequest\x1a\x16.otp.CreateOTPResponse\x12:\n" +
	"\tUpdateOTP\x12\x15.otp.UpdateOTPRequest\x1a\x16.otp.UpdateOTPResponse\x12:\n" +
	"\tDeleteOTP\x12\x15.otp.DeleteOTPRequest\x1a\x16.otp.DeleteOTPResponse\x121\n" +
	"\x06GetOTP\x12\x12.otp.GetOTPRequest\x1a\x13.otp.GetOTPResponse\x127\n" +
	"\bListOTPs\x12\x14.otp.ListOTPsRequest\x1a\x15.otp.ListOTPsResponse\x12=\n" +
	"\n" +
	"RequestOTP\x12\x16.otp.RequestOTPRequest\x1a\x17.otp.RequestOTPResponse\x12@\n" +
	"\vValidateOTP\x12\x17.otp.ValidateOTPRequest\x1a\x18.otp.ValidateOTPResponseB,Z*github.com/yasinsaee/go-user-service/otppbb\x06proto3"

var (
	file_user_service_otp_otp_proto_rawDescOnce sync.Once
	file_user_service_otp_otp_proto_rawDescData []byte
)

func file_user_service_otp_otp_proto_rawDescGZIP() []byte {
	file_user_service_otp_otp_proto_rawDescOnce.Do(func() {
		file_user_service_otp_otp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_otp_otp_proto_rawDesc), len(file_user_service_otp_otp_proto_rawDesc)))
	})
	return file_user_service_otp_otp_proto_rawDescData
}

var file_user_service_otp_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_user_service_otp_otp_proto_goTypes = []any{
	(*OTP)(nil),                 // 0: otp.OTP
	(*CreateOTPRequest)(nil),    // 1: otp.CreateOTPRequest
	(*CreateOTPResponse)(nil),   // 2: otp.CreateOTPResponse
	(*UpdateOTPRequest)(nil),    // 3: otp.UpdateOTPRequest
	(*UpdateOTPResponse)(nil),   // 4: otp.UpdateOTPResponse
	(*DeleteOTPRequest)(nil),    // 5: otp.DeleteOTPRequest
	(*DeleteOTPResponse)(nil),   // 6: otp.DeleteOTPResponse
	(*GetOTPRequest)(nil),       // 7: otp.GetOTPRequest
	(*GetOTPResponse)(nil),      // 8: otp.GetOTPResponse
	(*ListOTPsRequest)(nil),     // 9: otp.ListOTPsRequest
	(*ListOTPsResponse)(nil),    // 10: otp.ListOTPsResponse
	(*RequestOTPRequest)(nil),   // 11: otp.RequestOTPRequest
	(*RequestOTPResponse)(nil),  // 12: otp.RequestOTPResponse
	(*ValidateOTPRequest)(nil),  // 13: otp.ValidateOTPRequest
	(*ValidateOTPResponse)(nil), // 14: otp.ValidateOTPResponse
}
var file_user_service_otp_otp_proto_depIdxs = []int32{
	0,  // 0: otp.CreateOTPResponse.otp:type_name -> otp.OTP
	0,  // 1: otp.UpdateOTPResponse.otp:type_name -> otp.OTP
	0,  // 2: otp.GetOTPResponse.otp:type_name -> otp.OTP
	0,  // 3: otp.ListOTPsResponse.otps:type_name -> otp.OTP
	1,  // 4: otp.OTPService.CreateOTP:input_type -> otp.CreateOTPRequest
	3,  // 5: otp.OTPService.UpdateOTP:input_type -> otp.UpdateOTPRequest
	5,  // 6: otp.OTPService.DeleteOTP:input_type -> otp.DeleteOTPRequest
	7,  // 7: otp.OTPService.GetOTP:input_type -> otp.GetOTPRequest
	9,  // 8: otp.OTPService.ListOTPs:input_type -> otp.ListOTPsRequest
	11, // 9: otp.OTPService.RequestOTP:input_type -> otp.RequestOTPRequest
	13, // 10: otp.OTPService.ValidateOTP:input_type -> otp.ValidateOTPRequest
	2,  // 11: otp.OTPService.CreateOTP:output_type -> otp.CreateOTPResponse
	4,  // 12: otp.OTPService.UpdateOTP:output_type -> otp.UpdateOTPResponse
	6,  // 13: otp.OTPService.DeleteOTP:output_type -> otp.DeleteOTPResponse
	8,  // 14: otp.OTPService.GetOTP:output_type -> otp.GetOTPResponse
	10, // 15: otp.OTPService.ListOTPs:output_type -> otp.ListOTPsResponse
	12, // 16: otp.OTPService.RequestOTP:output_type -> otp.RequestOTPResponse
	14, // 17: otp.OTPService.ValidateOTP:output_type -> otp.ValidateOTPResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_service_otp_otp_proto_init() }
func file_user_service_otp_otp_proto_init() {
	if File_user_service_otp_otp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_otp_otp_proto_rawDesc), len(file_user_service_otp_otp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_otp_otp_proto_goTypes,
		DependencyIndexes: file_user_service_otp_otp_proto_depIdxs,
		MessageInfos:      file_user_service_otp_otp_proto_msgTypes,
	}.Build()
	File_user_service_otp_otp_proto = out.File
	file_user_service_otp_otp_proto_goTypes = nil
	file_user_service_otp_otp_proto_depIdxs = nil
}
