// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: user-service/otp/otp.proto

package otppb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OTPService_CreateOTP_FullMethodName   = "/otp.OTPService/CreateOTP"
	OTPService_UpdateOTP_FullMethodName   = "/otp.OTPService/UpdateOTP"
	OTPService_DeleteOTP_FullMethodName   = "/otp.OTPService/DeleteOTP"
	OTPService_GetOTP_FullMethodName      = "/otp.OTPService/GetOTP"
	OTPService_ListOTPs_FullMethodName    = "/otp.OTPService/ListOTPs"
	OTPService_RequestOTP_FullMethodName  = "/otp.OTPService/RequestOTP"
	OTPService_ValidateOTP_FullMethodName = "/otp.OTPService/ValidateOTP"
)

// OTPServiceClient is the client API for OTPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OTPServiceClient interface {
	CreateOTP(ctx context.Context, in *CreateOTPRequest, opts ...grpc.CallOption) (*CreateOTPResponse, error)
	UpdateOTP(ctx context.Context, in *UpdateOTPRequest, opts ...grpc.CallOption) (*UpdateOTPResponse, error)
	DeleteOTP(ctx context.Context, in *DeleteOTPRequest, opts ...grpc.CallOption) (*DeleteOTPResponse, error)
	GetOTP(ctx context.Context, in *GetOTPRequest, opts ...grpc.CallOption) (*GetOTPResponse, error)
	ListOTPs(ctx context.Context, in *ListOTPsRequest, opts ...grpc.CallOption) (*ListOTPsResponse, error)
	RequestOTP(ctx context.Context, in *RequestOTPRequest, opts ...grpc.CallOption) (*RequestOTPResponse, error)
	ValidateOTP(ctx context.Context, in *ValidateOTPRequest, opts ...grpc.CallOption) (*ValidateOTPResponse, error)
}

type oTPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOTPServiceClient(cc grpc.ClientConnInterface) OTPServiceClient {
	return &oTPServiceClient{cc}
}

func (c *oTPServiceClient) CreateOTP(ctx context.Context, in *CreateOTPRequest, opts ...grpc.CallOption) (*CreateOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOTPResponse)
	err := c.cc.Invoke(ctx, OTPService_CreateOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPServiceClient) UpdateOTP(ctx context.Context, in *UpdateOTPRequest, opts ...grpc.CallOption) (*UpdateOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOTPResponse)
	err := c.cc.Invoke(ctx, OTPService_UpdateOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPServiceClient) DeleteOTP(ctx context.Context, in *DeleteOTPRequest, opts ...grpc.CallOption) (*DeleteOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOTPResponse)
	err := c.cc.Invoke(ctx, OTPService_DeleteOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPServiceClient) GetOTP(ctx context.Context, in *GetOTPRequest, opts ...grpc.CallOption) (*GetOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOTPResponse)
	err := c.cc.Invoke(ctx, OTPService_GetOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPServiceClient) ListOTPs(ctx context.Context, in *ListOTPsRequest, opts ...grpc.CallOption) (*ListOTPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOTPsResponse)
	err := c.cc.Invoke(ctx, OTPService_ListOTPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPServiceClient) RequestOTP(ctx context.Context, in *RequestOTPRequest, opts ...grpc.CallOption) (*RequestOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestOTPResponse)
	err := c.cc.Invoke(ctx, OTPService_RequestOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPServiceClient) ValidateOTP(ctx context.Context, in *ValidateOTPRequest, opts ...grpc.CallOption) (*ValidateOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateOTPResponse)
	err := c.cc.Invoke(ctx, OTPService_ValidateOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OTPServiceServer is the server API for OTPService service.
// All implementations must embed UnimplementedOTPServiceServer
// for forward compatibility.
type OTPServiceServer interface {
	CreateOTP(context.Context, *CreateOTPRequest) (*CreateOTPResponse, error)
	UpdateOTP(context.Context, *UpdateOTPRequest) (*UpdateOTPResponse, error)
	DeleteOTP(context.Context, *DeleteOTPRequest) (*DeleteOTPResponse, error)
	GetOTP(context.Context, *GetOTPRequest) (*GetOTPResponse, error)
	ListOTPs(context.Context, *ListOTPsRequest) (*ListOTPsResponse, error)
	RequestOTP(context.Context, *RequestOTPRequest) (*RequestOTPResponse, error)
	ValidateOTP(context.Context, *ValidateOTPRequest) (*ValidateOTPResponse, error)
	mustEmbedUnimplementedOTPServiceServer()
}

// UnimplementedOTPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOTPServiceServer struct{}

func (UnimplementedOTPServiceServer) CreateOTP(context.Context, *CreateOTPRequest) (*CreateOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOTP not implemented")
}
func (UnimplementedOTPServiceServer) UpdateOTP(context.Context, *UpdateOTPRequest) (*UpdateOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOTP not implemented")
}
func (UnimplementedOTPServiceServer) DeleteOTP(context.Context, *DeleteOTPRequest) (*DeleteOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOTP not implemented")
}
func (UnimplementedOTPServiceServer) GetOTP(context.Context, *GetOTPRequest) (*GetOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOTP not implemented")
}
func (UnimplementedOTPServiceServer) ListOTPs(context.Context, *ListOTPsRequest) (*ListOTPsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOTPs not implemented")
}
func (UnimplementedOTPServiceServer) RequestOTP(context.Context, *RequestOTPRequest) (*RequestOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestOTP not implemented")
}
func (UnimplementedOTPServiceServer) ValidateOTP(context.Context, *ValidateOTPRequest) (*ValidateOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateOTP not implemented")
}
func (UnimplementedOTPServiceServer) mustEmbedUnimplementedOTPServiceServer() {}
func (UnimplementedOTPServiceServer) testEmbeddedByValue()                    {}

// UnsafeOTPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OTPServiceServer will
// result in compilation errors.
type UnsafeOTPServiceServer interface {
	mustEmbedUnimplementedOTPServiceServer()
}

func RegisterOTPServiceServer(s grpc.ServiceRegistrar, srv OTPServiceServer) {
	// If the following call pancis, it indicates UnimplementedOTPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OTPService_ServiceDesc, srv)
}

func _OTPService_CreateOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPServiceServer).CreateOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OTPService_CreateOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPServiceServer).CreateOTP(ctx, req.(*CreateOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPService_UpdateOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPServiceServer).UpdateOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OTPService_UpdateOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPServiceServer).UpdateOTP(ctx, req.(*UpdateOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPService_DeleteOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPServiceServer).DeleteOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OTPService_DeleteOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPServiceServer).DeleteOTP(ctx, req.(*DeleteOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPService_GetOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPServiceServer).GetOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OTPService_GetOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPServiceServer).GetOTP(ctx, req.(*GetOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPService_ListOTPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOTPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPServiceServer).ListOTPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OTPService_ListOTPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPServiceServer).ListOTPs(ctx, req.(*ListOTPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPService_RequestOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPServiceServer).RequestOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OTPService_RequestOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPServiceServer).RequestOTP(ctx, req.(*RequestOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPService_ValidateOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPServiceServer).ValidateOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OTPService_ValidateOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPServiceServer).ValidateOTP(ctx, req.(*ValidateOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OTPService_ServiceDesc is the grpc.ServiceDesc for OTPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OTPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "otp.OTPService",
	HandlerType: (*OTPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOTP",
			Handler:    _OTPService_CreateOTP_Handler,
		},
		{
			MethodName: "UpdateOTP",
			Handler:    _OTPService_UpdateOTP_Handler,
		},
		{
			MethodName: "DeleteOTP",
			Handler:    _OTPService_DeleteOTP_Handler,
		},
		{
			MethodName: "GetOTP",
			Handler:    _OTPService_GetOTP_Handler,
		},
		{
			MethodName: "ListOTPs",
			Handler:    _OTPService_ListOTPs_Handler,
		},
		{
			MethodName: "RequestOTP",
			Handler:    _OTPService_RequestOTP_Handler,
		},
		{
			MethodName: "ValidateOTP",
			Handler:    _OTPService_ValidateOTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-service/otp/otp.proto",
}
